apiVersion: v1
kind: ConfigMap
metadata:
  name: mlops-config
  namespace: mlops-monitoring
data:
  APP_ENV: "production"
  API_HOST: "0.0.0.0"
  API_PORT: "8080"
  MLFLOW_TRACKING_URI: "http://mlflow-server:5000"
  PROMETHEUS_URL: "http://prometheus:9090"
  LOG_LEVEL: "INFO"
  USE_SIMULATOR: "true"
