apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlops-artifacts-pvc
  namespace: mlops-monitoring
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-data-pvc
  namespace: mlops-monitoring
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi
